# This file is automatically generated by Posit Publisher; do not edit.
'$schema' = 'https://cdn.posit.co/publisher/schemas/posit-publishing-record-schema-v3.json'
server_type = 'connect_cloud'
server_url = 'https://connect.posit.cloud'
client_version = '1.22.0'
created_at = ''
dismissed_at = ''
type = 'python-shiny'
configuration_name = 'AI_Diagnosis_Demo-FL5A'
id = '01998e53-02e3-078e-3feb-7ba924b85f59'
dashboard_url = 'https://connect.posit.cloud/rana2hin/content/01998e53-02e3-078e-3feb-7ba924b85f59'
direct_url = 'https://01998e53-02e3-078e-3feb-7ba924b85f59.share.connect.posit.cloud'
logs_url = 'https://connect.posit.cloud/rana2hin/content/01998e53-02e3-078e-3feb-7ba924b85f59/history'
deployed_at = '2025-09-28T09:17:09+06:00'

[connect_cloud]
account_name = 'rana2hin'

[deployment_error]
code = 'unknown'
message = 'Open c:\Users\tuhin\Downloads\Py_Shiny\requirements.txt: The system cannot find the file specified.'
operation = ''

[configuration]
product_type = 'connect_cloud'
'$schema' = 'https://cdn.posit.co/publisher/schemas/posit-publishing-schema-v3.json'
type = 'python-shiny'
entrypoint = 'app.py'
validate = true
files = [
  '/app.py',
  '/requirements.txt',
  '/.posit/publish/AI_Diagnosis_Demo-FL5A.toml',
  '/.posit/publish/deployments/deployment-RMAS.toml',
  '/hypothetical_patient_data.csv',
  '/data_gen.py',
  '/.posit'
]
title = 'AI_Diagnosis_Demo'

[configuration.python]
version = '3.13'
